### ISSUE TITLE
enabled does not work

### ISSUE THREAD

**Issue by Fale** [AerisCloud/ansible-repos#11]
Using:

```

---
dependencies:
  - role: aeriscloud.repos
    repositories:
      centos6:
        - name: epel
          enabled: true
        - name: ius
          enabled: true
      centos7:
        - name: epel
          enabled: true
        - name: ius
          enabled: true
```

The result was:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [s01.locati.cc]

TASK: [aeriscloud.repos | Setup repositories] ********************************* 
skipping: [s01.locati.cc] => (item={'enabled': True, 'name': 'epel'})
skipping: [s01.locati.cc] => (item={'enabled': True, 'name': 'ius'})

TASK: [aeriscloud.repos | Setup GPG keys for repositories] ******************** 
skipping: [s01.locati.cc] => (item={'enabled': True, 'name': 'epel'})
skipping: [s01.locati.cc] => (item={'enabled': True, 'name': 'ius'})

TASK: [aeriscloud.repos | Setup remote repositories] ************************** 
skipping: [s01.locati.cc]

TASK: [aeriscloud.repos | Setup repositories] ********************************* 
fatal: [s01.locati.cc] => Failed to template {% if item in repository_list and centos_distribution in repository_list[item] %} True {% else %} False {% endif %}: an unexpected type error occurred. Error was unhashable type: 'dict'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/fale/site.retry

s01.locati.cc              : ok=3    changed=0    unreachable=1    failed=0 
```
